---
  - hosts: all
    sudo: true
    vars_files:
      - vars.yml
    tasks:
      - name: Apt update
        apt: update_cache=yes

      - name: Apt upgrade
        apt: upgrade=dist
    roles:
      - role: jdauphant.ssl-certs
      - role: jdauphant.nginx
